### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by Winwardo**

### CODE REVIEW

**Comment by Winwardo** [comment]
@Rultor please merge

**Comment by Winwardo** [comment]
@rultor hello

**Comment by Winwardo** [comment]
@rultor merge

**Comment by Winwardo** [comment]
@Rultor hello

**Comment by alexjneves** [comment]
@rultor try and merge this fool

**Comment by Winwardo** [comment]
@rultor merge please :+1:

**Comment by Winwardo** [comment]
@rultor merge

**Comment by Winwardo** [comment]
@rultor merge please

**Comment by Winwardo** [comment]
@rultor merge

**Comment by Winwardo** [comment]
@rultor merge

**Comment by Winwardo** [comment]
@rultor please merge

**Comment by Winwardo** [comment]
@rultor merge

**Pull request merged**
